import avatar from "../assets/imgs/avatar.png";
import home from "../assets/imgs/homeProp.png";
import home2 from "../assets/imgs/homeProp2.png";
import home3 from "../assets/imgs/homeProp3.png";

export const data = [
  {
    id: 1,
    homeImage: home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        maintitle: "Luxury Family Loft by Victoria Park",
        images: [home, home2, home3],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "130.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            airCondition: "Air Conditioning",
            icon: "icon condition",
          },
          {
            airCondition: "Barbeque",
            icon: "icon condition",
          },
          {
            airCondition: "Dryer",
            icon: "icon condition",
          },
          {
            airCondition: "Gym",
            icon: "icon condition",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    homeImage: home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 8,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "120.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            airCondition: "Air Conditioning",
            icon: "icon condition",
          },
          {
            airCondition: "Barbeque",
            icon: "icon condition",
          },
          {
            airCondition: "Dryer",
            icon: "icon condition",
          },
          {
            airCondition: "Gym",
            icon: "icon condition",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    homeImage: home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 5,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "140.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            airCondition: "Air Conditioning",
            icon: "icon condition",
          },
          {
            airCondition: "Barbeque",
            icon: "icon condition",
          },
          {
            airCondition: "Dryer",
            icon: "icon condition",
          },
          {
            airCondition: "Gym",
            icon: "icon condition",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    homeImage: home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 4,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "150.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            airCondition: "Air Conditioning",
            icon: "icon condition",
          },
          {
            airCondition: "Barbeque",
            icon: "icon condition",
          },
          {
            airCondition: "Dryer",
            icon: "icon condition",
          },
          {
            airCondition: "Gym",
            icon: "icon condition",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    homeImage: home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 2,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "155.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            airCondition: "Air Conditioning",
            icon: "icon condition",
          },
          {
            airCondition: "Barbeque",
            icon: "icon condition",
          },
          {
            airCondition: "Dryer",
            icon: "icon condition",
          },
          {
            airCondition: "Gym",
            icon: "icon condition",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    homeImage: home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 3,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "130.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            airCondition: "Air Conditioning",
            icon: "icon condition",
          },
          {
            airCondition: "Barbeque",
            icon: "icon condition",
          },
          {
            airCondition: "Dryer",
            icon: "icon condition",
          },
          {
            airCondition: "Gym",
            icon: "icon condition",
          },
        ],
      },
    ],
  },
];
