import avatar from "../assets/imgs/avatar.png";
import home from "../assets/imgs/homeProp.png";
import home2 from "../assets/imgs/homeProp2.png";
import home3 from "../assets/imgs/homeProp3.png";

export const data = [
  {
    id: 1,
    homeImage:home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    city: "Quincy St, Brooklyn, NY, USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
  },
  {
    id: 2,
    homeImage:home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    city: "Quincy St, Brooklyn, NY, USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
  },
  {
    id: 3,
    homeImage:home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    city: "Quincy St, Brooklyn, NY, USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
  },
  {
    id: 4,
    homeImage:home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    city: "Quincy St, Brooklyn, NY, USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
  },
  {
    id: 5,
    homeImage:home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    city: "Quincy St, Brooklyn, NY, USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
  },
  {
    id: 6,
    homeImage:home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    city: "Quincy St, Brooklyn, NY, USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
  },
];
