import avatar from "../assets/imgs/avatar.png";
import home from "../assets/imgs/homeProp.png";
import home2 from "../assets/imgs/homeProp2.png";
import home3 from "../assets/imgs/homeProp3.png";
import { ReactComponent as Condition } from "../assets/icons/air-conditioner 1.svg";
import { ReactComponent as Grass } from "../assets/icons/grass 1.svg";
import { ReactComponent as Refrigerator } from "../assets/icons/refrigerator.svg";
import { ReactComponent as Washer } from "../assets/icons/liquid-soap.svg";
import { ReactComponent as Barbeque } from "../assets/icons/barbecue 1.svg";
import { ReactComponent as Laundry } from "../assets/icons/laundry.svg";
import { ReactComponent as Sauna } from "../assets/icons/sauna.svg";
import { ReactComponent as Wife } from "../assets/icons/wifi.svg";
import { ReactComponent as Dryer } from "../assets/icons/dryer.svg";
import { ReactComponent as Microwave } from "../assets/icons/microwave.svg";
import { ReactComponent as Swimming } from "../assets/icons/swimmer.svg";
import { ReactComponent as Cover } from "../assets/icons/blinds.svg";
import { ReactComponent as Gym } from "../assets/icons/dumbbell.svg";
import { ReactComponent as Outdoor } from "../assets/icons/outdoor-shower.svg";
import { ReactComponent as Cable } from "../assets/icons/coaxial.svg";
import { ReactComponent as Chair } from "../assets/icons/chair.svg";

export const data = [
  {
    id: 1,
    homeImage: home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        maintitle: "Luxury Family Loft by Victoria Park",
        images: [home, home2, home3, home2, home, home3, home2, home, home3],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "130.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    homeImage: home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 8,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home3, home2, home, home3, home2, home],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "120.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,

            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    homeImage: home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 5,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "140.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,

            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    homeImage: home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 4,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "150.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    homeImage: home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 2,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "155.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    homeImage: home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 3,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "130.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    homeImage: home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 6,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        maintitle: "Luxury Family Loft by Victoria Park",
        images: [home, home2, home3, home2, home, home3, home2, home, home3],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "130.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 8,
    homeImage: home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 8,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home3, home2, home, home3, home2, home],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "120.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,

            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 9,
    homeImage: home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 5,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "140.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,

            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 10,
    homeImage: home3,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 4,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "150.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 11,
    homeImage: home2,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 2,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "155.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            condition: "Gym",
            conditionIcon: <Gym />,
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
  {
    id: 12,
    homeImage: home,
    title: "New Apartment Nice Wiew",
    user: avatar,
    price: "7,500",
    sale: "2.800",
    name: "Quincy St",
    city: "Brooklyn",
    address: "NY",
    country: "USA",
    avatar: "avatar",
    houseDetails: {
      beds: 3,
      baths: 2,
      garage: 1,
      area: 1400,
    },
    details: [
      {
        id: 1,
        images: [home, home2, home3, home2, home, home3, home2],
        houseDetails: {
          beds: 6,
          baths: 2,
          garage: 1,
          area: 1400,
          builtYear: 1800,
        },
        price: "7,500",
        oldPrice: "2,800",
        description:
          "Occupying over 8,000 square feet, perched over 1,100 feet in the air with absolutely breathtaking panoramic 360-degree views of all of New York City and the surrounding tri-state area, The 82nd Floor at 432 Park Avenue has been completely reimagined by one of the most sought-after design houses in London and represents an utterly unique opportunity to own a globally significant property. The residence is comprised of 5 bedrooms, 2 master bathrooms, 4 on-suite guest bathrooms, 2 powder rooms, 2 offices, 2 dressing rooms, a media room, an oversized eat-in gourmet chef's kitchen, and a sprawling 1,100 square-foot Great Room perfectly situated in the prime southwest corner of the floor.",
        documents: "dosc",
        address: "329 Queensberry Street",
        city: "Jersey City",
        area: "Greenville",
        state: "Washington",
        zip: "365448",
        country: "United States",
        propertyDetails: [
          {
            propertyId: "HZ27",
            Price: "130.000",
            PropertySize: "1560",
            YearBulit: "2021-01-09",
            Bedrooms: 8,
            Bathrooms: 6,
            Garage: 4,
            Garagesize: 200,
            PropertyType: "Apartment",
            PropertyStatus: "For Sale",
          },
        ],
        features: [
          {
            condition: "Air Conditioning",
            conditionIcon: <Condition />,
            lawn: "Lawn",
            lawnIcon: <Grass />,
            refrigerator: "Refrigerator",
            refrigeratorIcon: <Refrigerator />,
            washer: "Washer",
            washerIcon: <Washer />,
          },
          {
            condition: "Barbeque",
            conditionIcon: <Barbeque />,
            lawn: "Laundry",
            lawnIcon: <Laundry />,
            refrigerator: "Sauna",
            refrigeratorIcon: <Sauna />,
            washer: "WiFi",
            washerIcon: <Wife />,
          },
          {
            condition: "Dryer",
            conditionIcon: <Dryer />,
            lawn: "Microwave",
            lawnIcon: <Microwave />,
            refrigerator: "Swimming Pool",
            refrigeratorIcon: <Swimming />,
            washer: "Window Coverings",
            washerIcon: <Cover />,
          },
          {
            lawn: "Outdoor Shower",
            lawnIcon: <Outdoor />,
            refrigerator: "TV Cable",
            refrigeratorIcon: <Cable />,
            washer: "Dining room",
            washerIcon: <Chair />,
          },
        ],
      },
    ],
  },
];
